### ISSUE TITLE
Выдает ошибку

### ISSUE THREAD

**Issue by ianohin** [AlekseevAV/NooLite-telegram#1]
Перед этим во всех файлах пришлось прописывать в заголовке # -*- coding: utf-8 -*- ибо ничего не запускалось. Скрипт для ноолайта работает, но вот для бота выдает ошибку. Знаний для решения проблемы недостаточно:
` File "/home/ivan/.local/lib/python2.7/site-packages/telegram/ext/dispatcher.py", line 265, in process_update
    handler.handle_update(update, self)
  File "/home/ivan/.local/lib/python2.7/site-packages/telegram/ext/messagehandler.py", line 124, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "telegram_bot.py", line 60, in wrapped
    update.message.text if update.message else update.callback_query.data)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-9: ordinal not in range(128)`

**Comment by AlekseevAV** [comment]
Запускать нужно на python версии 3. Тогда и прописывать кодировку в начале файлов не нужно, и ошибки не должно такой возникнуть. На 2 версии не тестировал.
Если вдруг ошибка останется, то пишите.
